<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:fb="http://www.facebook.com/2008/fbml">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Yackety Yacc</title>
    <link href="/assets/stylesheets/reset.css" media="screen" rel="stylesheet" type="text/css" />
    <link href="/assets/stylesheets/screen.css" media="screen" rel="stylesheet" type="text/css" />
    <script src="/assets/javascripts/jquery-1.3.2.min.js" type="text/javascript"></script>
    <script src="/assets/javascripts/application.js" type="text/javascript"></script>
  </head>

  <body>
    <div class="wrapper">
      <div id="header-wrap">
        <div id="header">
          <h1><a href="/">Yackety Yacc</a></h1><span>Shave your urls and they'll purr like a Walrus.</span>
          <div id="top-nav">
            <ul>
              <li><a class="highlight" href="/about">What is Yackety Yacc?</a></li>
              <li><a class="highlight" href="http://github.com/abedra/yacketyya.cc/issues">Found a Bug?</a></li>
            </ul>
          </div>
        </div>
      </div>
      
      <div id="content-wrap">
        <div id="content">
