<div class="wrapper">
  <div id="header-wrap">
    <div id="header">
      <h1><a href="/">Yackety Yacc</a></h1><span>Shave your urls and they'll purr like a Walrus.</span>
      <div id="top-nav">
        <ul>
          <li><a class="highlight" href="/about">What is Yackety Yacc?</a></li>
          <li><a class="highlight" href="/instructions">How do I use this?</a></li>
          <li><a class="highlight" href="/contact">Contact</a></li>
        </ul>
      </div>
    </div>
  </div>

  <div id="content-wrap">
    <div id="content">
      <div id="url-form">
        <form action="/" method="POST" id="url-shortener">
          <div id="input-container">
            <input id="url" name="url" type="text" />
            <input type="button" value="Shave" id="submit" class="button" />
          </div>
          <div class="clearfix"></div>
        </form>
      </div>
      <div id="new-url"></div>
    </div>
  </div>
</div>
