<div id="url-form">
  <form action="/" method="POST" id="url-shortener">
    <div id="input-container">
      <input id="url" name="url" type="text" />
      <input type="button" value="Shave" id="submit" class="button" />
    </div>
    <div class="clearfix"></div>
  </form>
</div>
<div id="new-url"></div>
</div>

<div id="totals">
  <p><span id="total-urls">$total$</span> urls shorn to date, and many more to come!</p>
  <p>Copyright &copy 2009 Aaron Bedra</p>
</div>
